### ISSUE TITLE
[Assistance] with intersight_fabric_system_qos_policy class modification

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-intersight#106] opened 2021-06-27 12:43 UTC
I am struggling to figure out how to modify the classes with the system qos resource file.

Link to the source repository: https://github.com/scotttyso/terraform-intersight-imm/tree/master/modules/domain_system_qos

This is the output of the main.tf file

```
resource "intersight_fabric_system_qos_policy" "system_qos" {
  description = var.description
  name        = var.name
  organization {
    moid        = var.org_moid
    object_type = "organization.Organization"
  }
  dynamic "classes" {
    for_each = var.classes
    content {
      admin_state        = classes.value.admin_state
      bandwidth_percent  = classes.value.bandwidth_percent
      cos                = classes.value.cos
      mtu                = classes.value.mtu
      multicast_optimize = classes.value.multicast_optimize
      name               = classes.value.name
      object_type        = "fabric.QosClass"
      packet_drop        = classes.value.packet_drop
      weight             = classes.value.weight
    }
  }
  dynamic "profiles" {
    for_each = var.profiles
    content {
      moid        = profiles.value.moid
      object_type = profiles.value.object_type
    }
  }
  dynamic "tags" {
    for_each = var.tags
    content {
      key   = tags.value.key
      value = tags.value.value
    }
  }
}

```

And here is my module that is consuming it

```
module "system_qos_example" {
  depends_on = [
    data.intersight_organization_organization.org_moid
  ]
  source      = "../../modules/policies_system_qos"
  description = "System QoS Default Example."
  name        = "example"
  org_moid    = local.org_moid
  profiles    = var.profiles
  tags        = var.tags
  classes = [
    {
      admin_state        = "Enabled"
      bandwidth_percent  = 22
      cos                = 5
      mtu                = 9216
      multicast_optimize = false
      name               = "Platinum"
      packet_drop        = true
      weight             = 10
    },
    {
      admin_state        = "Enabled"
      bandwidth_percent  = 20
      cos                = 4
      mtu                = 9216
      multicast_optimize = false
      name               = "Gold"
      packet_drop        = true
      weight             = 9
    },
    {
      admin_state        = "Enabled"
      bandwidth_percent  = 18
      cos                = 2
      mtu                = 1500
      multicast_optimize = false
      name               = "Silver"
      packet_drop        = true
      weight             = 8
    },
    {
      admin_state        = "Disabled"
      bandwidth_percent  = 15
      cos                = 1
      mtu                = 9216
      multicast_optimize = false
      name               = "Bronze"
      packet_drop        = true
      weight             = 7
    },
    {
      admin_state        = "Enabled"
      bandwidth_percent  = 11
      cos                = 255
      mtu                = 9216
      multicast_optimize = false
      name               = "Best Effort"
      packet_drop        = true
      weight             = 5
    },
    {
      admin_state        = "Enabled"
      bandwidth_percent  = 14
      cos                = 3
      mtu                = 2240
      multicast_optimize = false
      name               = "FC"
      packet_drop        = false
      weight             = 5
    },
  ]
}

```

If I remove all of the classes then the apply works fine.  But even with the classes in place a plan looks like it is going to work but it fails on apply.

Here is the output from a terraform plan

```
  # module.system_qos_example.intersight_fabric_system_qos_policy.system_qos will be created
  + resource "intersight_fabric_system_qos_policy" "system_qos" {
      + account_moid         = (known after apply)
      + ancestors            = (known after apply)
      + class_id             = "fabric.SystemQosPolicy"
      + classes              = [
          + {
              + additional_properties = null
              + admin_state           = "Enabled"
              + bandwidth_percent     = 22
              + class_id              = "fabric.QosClass"
              + cos                   = 5
              + mtu                   = 9216
              + multicast_optimize    = false
              + name                  = "Platinum"
              + object_type           = "fabric.QosClass"
              + packet_drop           = true
              + weight                = 10
            },
          + {
              + additional_properties = null
              + admin_state           = "Enabled"
              + bandwidth_percent     = 20
              + class_id              = "fabric.QosClass"
              + cos                   = 4
              + mtu                   = 9216
              + multicast_optimize    = false
              + name                  = "Gold"
              + object_type           = "fabric.QosClass"
              + packet_drop           = true
              + weight                = 9
            },
          + {
              + additional_properties = null
              + admin_state           = "Enabled"
              + bandwidth_percent     = 18
              + class_id              = "fabric.QosClass"
              + cos                   = 2
              + mtu                   = 1500
              + multicast_optimize    = false
              + name                  = "Silver"
              + object_type           = "fabric.QosClass"
              + packet_drop           = true
              + weight                = 8
            },
          + {
              + additional_properties = null
              + admin_state           = "Disabled"
              + bandwidth_percent     = 15
              + class_id              = "fabric.QosClass"
              + cos                   = 1
              + mtu                   = 9216
              + multicast_optimize    = false
              + name                  = "Bronze"
              + object_type           = "fabric.QosClass"
              + packet_drop           = true
              + weight                = 7
            },
          + {
              + additional_properties = null
              + admin_state           = "Enabled"
              + bandwidth_percent     = 11
              + class_id              = "fabric.QosClass"
              + cos                   = 255
              + mtu                   = 9216
              + multicast_optimize    = false
              + name                  = "Best Effort"
              + object_type           = "fabric.QosClass"
              + packet_drop           = true
              + weight                = 5
            },
          + {
              + additional_properties = null
              + admin_state           = "Enabled"
              + bandwidth_percent     = 14
              + class_id              = "fabric.QosClass"
              + cos                   = 3
              + mtu                   = 2240
              + multicast_optimize    = false
              + name                  = "FC"
              + object_type           = "fabric.QosClass"
              + packet_drop           = false
              + weight                = 5
            },
        ]
      + create_time          = (known after apply)
      + description          = "System QoS Default Example."
      + domain_group_moid    = (known after apply)
      + id                   = (known after apply)
      + mod_time             = (known after apply)
      + moid                 = (known after apply)
      + name                 = "example"
      + object_type          = "fabric.SystemQosPolicy"
      + organization         = [
          + {
              + additional_properties = null
              + class_id              = "mo.MoRef"
              + moid                  = "60aeca786972652d32ee5e46"
              + object_type           = "organization.Organization"
              + selector              = null
            },
        ]
      + owners               = (known after apply)
      + parent               = (known after apply)
      + permission_resources = (known after apply)
      + profiles             = (known after apply)
      + shared_scope         = (known after apply)
      + tags                 = [
          + {
              + additional_properties = null
              + key                   = "Terraform"
              + value                 = "Module"
            },
          + {
              + additional_properties = null
              + key                   = "Owner"
              + value                 = "tyscott"
            },
        ]
      + version_context      = (known after apply)
    }
```

Here is the error when attempting an apply

```
╷
│ Error: error occurred while creating FabricSystemQosPolicy: 400 Bad Request Response from endpoint: {"code":"InternalServerError","message":"Cannot create custom QoS Classes under the System QoS Policy: example","messageId":"gobi_fabric_qos_class_add","messageParams":{"1":"example"},"traceId":"NB6795aee7742d51680267f6d6d88e4f38"}
│ 
│   with module.system_qos_example.intersight_fabric_system_qos_policy.system_qos,
│   on ../../modules/domain_system_qos/main.tf line 7, in resource "intersight_fabric_system_qos_policy" "system_qos":
│    7: resource "intersight_fabric_system_qos_policy" "system_qos" {
│ 

```

Looking for some guidance here

**Comment by code-lucidal58** [comment] 2021-07-06 06:58
While creating an object of FabricSystemQosPolicy, the endpoint sets values for the `Class` property. The service is designed to throw an error if the user tries to set the property. However, the user is allowed to edit the values of the endpoint-populated values as an update request. In terms of Terraform, 1) `terraform apply` without the class values. 2) `terraform apply` after updating the configuration with the desired values, should work.

A discussion thread is ongoing to fix this issue from the backend.

**Comment by meghana-rajashekar** [comment] 2021-09-15 11:09
#### The issue is now fixed by the backend. Below is the config tried on the latest provider version: 1.0.15

```hcl-terraform
module "system_qos_example" {
  depends_on = [
    data.intersight_organization_organization.default_org
  ]
  source      = "../../modules/system_qos_policies"
  description = "System QoS Default Example."
  name        = "example"
  org_moid    = data.intersight_organization_organization.default_org.results.0.moid
  tags        = var.tags
  classes  = {
    Platinum = {
      state        = "Enabled"
      bandwidth_percent  = 22
      cos                = 5
      mtu                = 9216
      multicast_optimize = false
      packet_drop        = true
      weight             = 10
    }
    Gold = {
      state        = "Enabled"
      bandwidth_percent  = 20
      cos                = 4
      mtu                = 9216
      multicast_optimize = false
      packet_drop        = true
      weight             = 9
    }
    Silver = {
      state        = "Enabled"
      bandwidth_percent  = 18
      cos                = 2
      mtu                = 1500
      multicast_optimize = false
      packet_drop        = true
      weight             = 8
    }
    Bronze = {
      state        = "Disabled"
      bandwidth_percent  = 15
      cos                = 1
      mtu                = 9216
      multicast_optimize = false
      packet_drop        = true
      weight             = 7
    }
    "Best Effort" = {
      state        = "Enabled"
      bandwidth_percent  = 11
      cos                = 255
      mtu                = 9216
      multicast_optimize = false
      packet_drop        = true
      weight             = 5
    }
    FC = {
      state        = "Enabled"
      bandwidth_percent  = 14
      cos                = 3
      mtu                = 2240
      multicast_optimize = false
      packet_drop        = false
      weight             = 5
    }
  }
}
```

#### And here is the output on terraform apply:
```bash
# module.system_qos_example.intersight_fabric_system_qos_policy.classes will be created
  + resource "intersight_fabric_system_qos_policy" "classes" {
      + account_moid         = (known after apply)
      + ancestors            = (known after apply)
      + class_id             = "fabric.SystemQosPolicy"
      + classes              = [
          + {
              + additional_properties = ""
              + admin_state           = "Enabled"
              + bandwidth_percent     = 11
              + class_id              = "fabric.QosClass"
              + cos                   = 255
              + mtu                   = 9216
              + multicast_optimize    = false
              + name                  = "Best Effort"
              + object_type           = "fabric.QosClass"
              + packet_drop           = true
              + weight                = 5
            },
          + {
              + additional_properties = ""
              + admin_state           = "Disabled"
              + bandwidth_percent     = 15
              + class_id              = "fabric.QosClass"
              + cos                   = 1
              + mtu                   = 9216
              + multicast_optimize    = false
              + name                  = "Bronze"
              + object_type           = "fabric.QosClass"
              + packet_drop           = true
              + weight                = 7
            },
          + {
              + additional_properties = ""
              + admin_state           = "Enabled"
              + bandwidth_percent     = 14
              + class_id              = "fabric.QosClass"
              + cos                   = 3
              + mtu                   = 2240
              + multicast_optimize    = false
              + name                  = "FC"
              + object_type           = "fabric.QosClass"
              + packet_drop           = false
              + weight                = 5
            },
          + {
              + additional_properties = ""
              + admin_state           = "Enabled"
              + bandwidth_percent     = 20
              + class_id              = "fabric.QosClass"
              + cos                   = 4
              + mtu                   = 9216
              + multicast_optimize    = false
              + name                  = "Gold"
              + object_type           = "fabric.QosClass"
              + packet_drop           = true
              + weight                = 9
            },
          + {
              + additional_properties = ""
              + admin_state           = "Enabled"
              + bandwidth_percent     = 22
              + class_id              = "fabric.QosClass"
              + cos                   = 5
              + mtu                   = 9216
              + multicast_optimize    = false
              + name                  = "Platinum"
              + object_type           = "fabric.QosClass"
              + packet_drop           = true
              + weight                = 10
            },
          + {
              + additional_properties = ""
              + admin_state           = "Enabled"
              + bandwidth_percent     = 18
              + class_id              = "fabric.QosClass"
              + cos                   = 2
              + mtu                   = 1500
              + multicast_optimize    = false
              + name                  = "Silver"
              + object_type           = "fabric.QosClass"
              + packet_drop           = true
              + weight                = 8
            },
        ]
      + create_time          = (known after apply)
      + description          = "System QoS Default Example."
      + domain_group_moid    = (known after apply)
      + id                   = (known after apply)
      + mod_time             = (known after apply)
      + moid                 = (known after apply)
      + name                 = "example"
      + object_type          = "fabric.SystemQosPolicy"
      + organization         = [
          + {
              + additional_properties = null
              + class_id              = "mo.MoRef"
              + moid                  = "5daa09956972652d314fdac4"
              + object_type           = "organization.Organization"
              + selector              = null
            },
        ]
      + owners               = (known after apply)
      + parent               = (known after apply)
      + permission_resources = (known after apply)
      + profiles             = (known after apply)
      + shared_scope         = (known after apply)
      + tags                 = (known after apply)
      + version_context      = (known after apply)
    }

  # module.system_qos_example.intersight_fabric_system_qos_policy.system_qos will be created
  + resource "intersight_fabric_system_qos_policy" "system_qos" {
      + account_moid         = (known after apply)
      + ancestors            = (known after apply)
      + class_id             = "fabric.SystemQosPolicy"
      + classes              = (known after apply)
      + create_time          = (known after apply)
      + description          = "System QoS Default Example."
      + domain_group_moid    = (known after apply)
      + id                   = (known after apply)
      + mod_time             = (known after apply)
      + moid                 = (known after apply)
      + name                 = "example"
      + object_type          = "fabric.SystemQosPolicy"
      + organization         = [
          + {
              + additional_properties = null
              + class_id              = "mo.MoRef"
              + moid                  = "5daa09956972652d314fdac4"
              + object_type           = "organization.Organization"
              + selector              = null
            },
        ]
      + owners               = (known after apply)
      + parent               = (known after apply)
      + permission_resources = (known after apply)
      + profiles             = (known after apply)
      + shared_scope         = (known after apply)
      + tags                 = (known after apply)
      + version_context      = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

If you are still facing any issue, please provide more details on the provider version and the tf module used.

**Closed** 2021-11-11 04:46 UTC
Labels: intersight-backend-fix
