### ISSUE TITLE
[ISSUE] BIOS Policy cannot be applied for CVA due to property does not exist.

### ISSUE THREAD

**Issue by erqiyang** [CiscoDevNet/terraform-provider-intersight#221] opened 2022-09-08 03:58 UTC
##### Description

When applying a bios policy with no other arguments (i.e, implying platform-default for all arguments) on a Connected Virtual Appliance, received a ```400 Bad Request Response``` error message. (see below). It indicates that some property on the BIOS policy does not exist. Have only seen it mentioned ```bios.Policy:CpuPaLimit``` or ```bios.Policy:TpmPpiRequired``` so far.

This issue only occurs on CVA, (and possibly PVA as well). It does not happen on Saas.

This is kinda a deal breaker for trying to implement IaaC.

##### Terraform-provider-intersight version

1.0.32

##### Configuration file
```
resource "intersight_bios_policy" "default" {
  name = "bios-default"
  description = "Default BIOS Policy"
  organization {
    moid = intersight_organization_organization.org.moid
  }
}
```

##### Actual output (Attach screenshots if applicable)

```
╷
│ Error: error occurred while creating BiosPolicy: 400 Bad Request Response from endpoint: {"code":"InvalidRequest","message":"Cannot create or modify the object ''. The property 'bios.Policy:CpuPaLimit' does not exist.","messageId":"barcelona_request_property_does_not_exist","messageParams":{"1":"","2":"bios.Policy","3":"CpuPaLimit"},"traceId":"NB0bc8cbee10e73286333c9294fd7fa399"}
│ 
│   with intersight_bios_policy.default,
│   on policy_bios.tf line 1, in resource "intersight_bios_policy" "default":
│    1: resource "intersight_bios_policy" "default" {
│ 
╵
```

or 

```
╷
│ Error: error occurred while creating BiosPolicy: 400 Bad Request Response from endpoint: {"code":"InvalidRequest","message":"Cannot create or modify the object ''. The property 'bios.Policy:TpmPpiRequired' does not exist.","messageId":"barcelona_request_property_does_not_exist","messageParams":{"1":"","2":"bios.Policy","3":"TpmPpiRequired"},"traceId":"NB6ba8c476dcbcf2ad16a563a03312e54b"}
│ 
│   with intersight_bios_policy.default,
│   on policy_bios.tf line 1, in resource "intersight_bios_policy" "default":
│    1: resource "intersight_bios_policy" "default" {
│ 
╵
```

##### Related issues/PRs

Not found

##### Suggest a fix

Can't tell if it's backend issue. But when comparing Saas and CVA, obvious disparity between available configurable property.

**Comment by meghana-rajashekar** [comment] 2022-09-20 04:13
@erqiyang - Unable to reproduce the issue. 
Could you help with the right setup ?

**Comment by scotttyso** [comment] 2022-10-06 20:55
@erqiyang - The issue is this is a new BIOS token that hasn't been published to the API yet for the CVA.  you need to wait for the next update and the issue will be resolved.  Or set the provider version back to version 1.0.28 or something like that.

**Comment by erqiyang** [comment] 2022-10-10 23:17
@meghana-rajashekar , It should be repeatable with the latest version of Intersight CVA and terraform provider version 1.0.32 .

@scotttyso , Thanks for your input. You are right. An earlier version works. Specifically, version 1.0.30 . Any earlier and it starts causing issue with other resources.

**Comment by scotttyso** [comment] 2024-01-17 23:27
@erqiyang - I think this issue should be closed.  There is another request:
https://github.com/CiscoDevNet/terraform-provider-intersight/issues/254

That really is the root of what you are asking for, and that can be tracked without keeping this open

**Comment by scotttyso** [comment] 2024-06-01 13:12
@vvb - Please close this issue the answer has already been provided

**Comment by polly73** [comment] 2024-06-11 09:54
I stumpled since days over the problem, that i couldnt deploy a bios policy with the latest intersight provider 1.0.50 with a connected private virtual appliance. 
Going back to intersight provider 1.0.35 worked for me now, but this case is open since October 2022.

**Comment by scotttyso** [comment] 2024-06-11 11:08
@polly73 

So this isn't super intuitive.  But you need to Login to the PVA and look at the API Reference Version.
Go to Help Center > Help Center.  Under Getting Started Click on API Documentation.  At the top of the page click on API Reference.  Under the Search box you will see the Version of the API that is currently running on the appliance.  i.e. something like API Reference v1.0.11-17057, which is what is currently running on SaaS.

Next go to the releases on GitHub Here:
https://github.com/CiscoDevNet/terraform-provider-intersight/releases

This will list under each release, which version of the API is supported: i.e.
v1.0.50: Refreshes the provider for Intersight version 17057

Match the Intersight Version to the Version shown in your API.  That is what is necessary to do for confirming the supported release.

I hope they do something to publish this on the module in the registry, but for now this is how you can get your answer.

**Closed** 2024-08-22 05:56 UTC
