### ISSUE TITLE
[BUG] Domain Profile (intersight_fabric_switch_profile) policy_bucket fails silently [Backend: INTERSIGHT-9800]

### ISSUE THREAD

**Issue by jerewill-cisco** [CiscoDevNet/terraform-provider-intersight#166] opened 2022-02-02 17:01 UTC
**Description**
Policies attached to the domain profile using the using the policy_bucket syntax in the intersight_fabric_switch_profile resource do not generate any errors and yet are not attached.

**To Reproduce**
```
resource "intersight_fabric_port_policy" "default-6454" {
  name         = "default-6454"
  device_model = "UCS-FI-6454"
}

resource "intersight_fabric_switch_profile" "example" {
  for_each = toset(["A", "B"])
  name = "example-${each.key}"
  type = "instance"
  policy_bucket {
    moid        = intersight_fabric_port_policy.default-6454.moid
    object_type = intersight_fabric_port_policy.default-6454.object_type
  }
}
```

**Expected behavior**
The expected behavior is clearly that the policy would be attached to the profile when using the policy_bucket syntax.  Also, if the policy cannot be attached, the resource creation must fail.

**Provider Version :** v1.0.22

**Additional context**
This bug does have a workaround but that workaround creates a policy inversion that is undesirable in the Terraform resource model.  Normally, the TF configuration for Intersight would follow a policy consumption model.  In that model, the policy objects would be created as resources and the various profiles would consume them as they are created.  The profiles should naturally depend on the policies.  The current behavior requires that model to be inverted and the policy resources become dependent on the profiles which is both programmatically undesirable as well as unintuitive.  The workaround for this bug looks something like this...

```
resource "intersight_fabric_switch_profile" "example" {
  for_each = toset(["A", "B"])
  name = "example-${each.key}"
  type = "instance"
}

resource "intersight_fabric_port_policy" "default-6454" {
  name         = "default-6454"
  device_model = "UCS-FI-6454"

  # This is a temporary workaround to the bug in intersight_fabric_switch_profile policy_bucket
  # we are attaching the profile to the policy here instead of attaching the policy to the profile
  dynamic "profiles" {
    for_each = intersight_fabric_switch_profile.example
    content {
      moid        = profiles.value.moid
      object_type = profiles.value.object_type
    }
  }
}
```

**Comment by thjonson** [comment] 2023-02-06 17:29
Just ran into this issue.  It would be great to get this resolved, or we should at least update the documentation to indicate the policy_bucket option does not work with the fabric_switch_profile.  It seems to take, and even reflects correctly in the API, it just doesn't work.

**Comment by vvb** [comment] 2024-01-08 09:06
I am checking with the backend team on this. The issue is with the backend API here.

**Comment by scotttyso** [comment] 2024-01-08 13:30
@thjonson and @vvb, if you are using v1.0.22 or greater for the provider this should be fixed.  This has been fixed for quite a while.  This wasn't a bug with the provider it was a bug with the Intersight API.

@thjonson there is a new issue that the domain profile will fail if you assign serial numbers at the same time, you create the domain profile.  I will have to check and see if this is filed or not.  I had raised this new issue internally, but I don't know if I opened a new bug, since it is again a bug with the API, not the provider.  Can you provide more details on exactly what you are seeing?

**Comment by scotttyso** [comment] 2024-01-17 22:42
@vvb - this issue is fixed.  Shouldn't this be closed?

**Comment by scotttyso** [comment] 2024-01-17 23:31
@vvb and @jerewill-cisco - this is fixed.  Will you close this.

**Closed** 2024-01-18 14:28 UTC
Labels: bug, intersight-backend-fix
