### ISSUE TITLE
Resource intersight_bios_policy doesn't apply/update tags attribute

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/terraform-provider-intersight#49] opened 2021-02-20 21:24 UTC
-Created a simple bios policy with 2 tags. Terraform plan and apply command shows the change but it doesn't reflect in the BIOS policy. 
-The BIOS policy is missing the tag values. 
-Additionally, the tags were not applied in the BIOS policy creation as well. 

**Issue:** terraform provider doesn't apply/update tag attributes in the BIOS policy. 

------------------------------------------------------------------------

resource "intersight_bios_policy" "bios_policy" {
  name        = "tf_bios_policy"
  description = "tf BIOS Policy"
  organization {
    object_type = "organization.Organization"
  }
  tags {
    key   = "test1"  
    value = "value2" 
  }
  tags {
    key   = "test2"  
    value = "value3" 
  }
  cpu_power_management = "performance"
  serial_port_aenable  = "enabled"
}

------------------------------------------------------------------------

% terraform plan
intersight_bios_policy.bios_policy: Refreshing state... [id=xxxxx]
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

   intersight_bios_policy.bios_policy will be updated in-place
  ~ resource "intersight_bios_policy" "bios_policy" {
        id                                    = "xxxxxxxxx"
        name                                  = "tf_sj_bios_policy"
        # (303 unchanged attributes hidden)

      ~ tags {
          ~ value = "value1" -> "value2"
            # (1 unchanged attribute hidden)
        }
      ~ tags {
          ~ value = "value2" -> "value3"
            # (1 unchanged attribute hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

% terraform apply              
intersight_bios_policy.bios_policy: Refreshing state... [id=xxxxxxx]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  intersight_bios_policy.bios_policy will be updated in-place
  ~ resource "intersight_bios_policy" "bios_policy" {
        id                                    = "xxxxxxx"
        name                                  = "tf_sj_bios_policy"
        # (303 unchanged attributes hidden)

      ~ tags {
          ~ value = "value1" -> "value2"
            # (1 unchanged attribute hidden)
        }
      ~ tags {
          ~ value = "value2" -> "value3"
            # (1 unchanged attribute hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

intersight_bios_policy.bios_policy: Modifying... [id=xxxxxx]
intersight_bios_policy.bios_policy: Modifications complete after 1s [id=xxxxxxx]

------------------------------------------------------------------------

**Comment by code-lucidal58** [comment] 2021-03-18 05:46
Using the same configuration and provider version 1.0.2, the issue is not found. Hence, it is fixed in the latest provider version. Closing this issue now.

**Closed by code-lucidal58** 2021-03-18 05:46 UTC
