### ISSUE TITLE
[BUG] Optional Properties for HX Cluster Profile not set to computed

### ISSUE THREAD

**Issue by techBeck03** [CiscoDevNet/terraform-provider-intersight#89] opened 2021-05-11 12:16 UTC
**Describe the bug**
In the `intersight_hyperflex_cluster_profile` resource the following optional properties should also be set to computed.

- `action`
- `replication`
- `data_ip_address`

**To Reproduce**
1. Create `intersight_hyperflex_cluster_profile`
2. Run `terraform apply`
3. Run `terraform apply` again

**Expected behavior**
There should be no diffs on the subsequent apply

**Screenshots and Terraform configurations**
```bash
# module.hx-cluster.intersight_hyperflex_cluster_profile.hx_cluster_profile will be updated in-place
  ~ resource "intersight_hyperflex_cluster_profile" "hx_cluster_profile" {
      - action                     = "No-op" -> null
      - data_ip_address            = "169.254.239.1" -> null
        id                         = "604821bf6973682d305ac983"
        name                       = "fury-hx-cluster"
      - replication                = 3 -> null
        tags                       = []
      + wait_for_completion        = true
        # (43 unchanged attributes hidden)
    }
```

**Provider Version :** v1.0.8

**Additional context**

**Comment by meghana-rajashekar** [comment] 2022-02-23 05:29
@techBeck03 These diffs were because few of the attributes were being set to default values from the backend.
Since config file would not include these, it would show the diff between the value set from the backend and empty values from config. 
#### However, this issue has been resolved in the latest provider release(1.0.23) to explicitly ignore the attributes with default values from backend if not set in the config file. 
- [x] Expected behavior: There should be no diffs on the subsequent apply

**Closed by meghana-rajashekar** 2022-02-23 05:29 UTC
Labels: enhancement
